---
title: "Single Cell RNA-seq Trajectory With Monocle"
author: "Zain Arifin"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(SeuratData)
library(patchwork)
library(tidyverse)
library(SeuratWrappers)
library(monocle3)
```

## Single Cell Analysis

```{r load-data, warning=F}
InstallData("ifnb")
LoadData("ifnb")

# In this dataset, the source of batch is stimulation condition
ifnb.list <- SplitObject(ifnb, split.by = "stim")
```

## Quality control

```{r}

# normalize and identify variable features for each dataset independently
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 3000)
})

# select features that are repeatedly variable across datasets for integration run PCA on each
# dataset using these features
features <- SelectIntegrationFeatures(object.list = ifnb.list)
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE)
})

#use rpca for fast integration
immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, 
                                         anchor.features = features, 
                                         reduction = "rpca", k.anchor = 25)
# this command creates an 'integrated' data assay
immune.combined <- IntegrateData(anchorset = immune.anchors)

# specify that we will perform downstream analysis on the corrected data note that the
# original unmodified data still resides in the 'RNA' assay
DefaultAssay(immune.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindClusters(immune.combined, resolution = 0.7)
```

## Trajectory Analysis with Monocle3

Pseudotime inference with Monocle for cell trajectory construction.

```{r}
DefaultAssay(object = immune.combined) <- "RNA"
seurat_cds <- as.cell_data_set(immune.combined)
seurat_cds <- cluster_cells(cds = seurat_cds, reduction_method = "UMAP")
seurat_cds <- learn_graph(seurat_cds, use_partition = TRUE)

seurat_cds <- order_cells(seurat_cds, reduction_method = "UMAP")

plot_cells(
  cds = seurat_cds,
  color_cells_by = "pseudotime",
  show_trajectory_graph = F
)
```

